### ISSUE TITLE
Add email and password to login func to login

### ISSUE THREAD

**Issue by StefMa** [felixstrobel/mailtm#1]
mail.tm can also be used to "login" again.
You only have to store your email adress and password somewhere and you can login with that account.
This library doesn't support it yet
https://github.com/felixstrobel/mailtm/blob/1e56d28311f79551d98be65af18383bd39fd45a3/mailtm.go#L159-L164
`Login()` uses the stored email and password from the `Register()` function.

We should change the `Login()` function (or add another) to login like
```go
func Login(email, password string) error {
  // Do the login magic
}
```

`Login()` should then called automatically inside the `Register()` function so that a client don't have to call it.
The new API should look like:
```
// Either you Register a new mail
GetDomains()
Register(...)
GetMessages()

// Or you Login with an existing email
Login(...)
GetMessages()
```

Does this make sense? 🤔

**Comment by felixstrobel** [comment]
This has been fixed in v2.
