### ISSUE TITLE
Getting `Message` by ID does not contain the `text` (content) of the email

### ISSUE THREAD

**Issue by StefMa** [felixstrobel/mailtm#3]
`GetMessages(page)` returns a slice of a `Message`:
https://github.com/felixstrobel/mailtm/blob/1e56d28311f79551d98be65af18383bd39fd45a3/mailtm.go#L227-L237

`GetMessage(messageId)` returns the same `Message` object:
https://github.com/felixstrobel/mailtm/blob/1e56d28311f79551d98be65af18383bd39fd45a3/mailtm.go#L257-L269

But according to the [mail.tm API](api.mail.tm) the responses differ from each other.
The message returned by `id` (`/message/{id}`) contains also `text` and `html`.
![Screenshot 2022-01-05 at 08 28 10](https://user-images.githubusercontent.com/10229883/148177346-9fa6a212-6f0d-4575-91e1-804ee9fe0da5.png)

This library should either:
* Map the `Message` from `/messages` directly to the `/messages/{id}` structs.
* Return a different `Message` struct when getting a message via `/message/{id}` which contains additional params.

Both solutions are fine.
What would you prefer?

**Comment by felixstrobel** [comment]
Version 2 handles the two different responses

**Comment by StefMa** [comment]
Nice job! 👏 
Seems you went with the second proposal.
I'm fine with that ✅ 

Thanks for the fast response!
