### ISSUE TITLE
Remove debug logging or introduce a `logger`

### ISSUE THREAD

**Issue by StefMa** [felixstrobel/mailtm#5]
Version 2 (as well as current `master`) contains a few debug messages. E.g.
https://github.com/felixstrobel/mailtm/blob/00fdce666fab37804f3381dfbe8fce8b69c4cb33/domains.go#L50

Would be cool if you could either:
* Remove it
* Introduce a logger to the library which we can set to decide where to log the stuff (in a file, stdout, ...?)

**Comment by felixstrobel** [comment]
Fixed in e5d5628d24b8f3505e61d8b7f60d2b3c0e809201
