### ISSUE TITLE
GetAuthTokenCredentials does not return an error for status 401

### ISSUE THREAD

**Issue by rumourscape** [felixstrobel/mailtm#8]
GetAuthTokenCredentials function returns a blank token and a nil error if mail.tm returns an unauthorized (401) error.

**Comment by saadi925** [comment]
yes , i have been facing the same issue besides it is not generating a valid email also , when we create an account

**Comment by felixstrobel** [comment]
I never had any problems with generating an email. They were all valid. How often does it happen to you?
I hope the #10 commit fixed the issue with the `GetAuthTokenCredentials`. You don't have to fetch the token by yourself; you can still access it but you don't have to anymore. However, the auth flow is different now. Please check the README.
