### ISSUE TITLE
GetMessages can't be serialized 

### ISSUE THREAD

**Issue by StefMa** [felixstrobel/mailtm#9]
Seems something changed. When I try to get messages I get a serialized error...

**Comment by rumourscape** [comment]
The detailed messages struct has a Test field which should actually be Text field. I believe that's the issue.

**Comment by rumourscape** [comment]
Never mind, I was using v0.2 which had that bug.

**Comment by StefMa** [comment]
I found the problem.
I used a zero in `GetMessages(page)`
https://github.com/felixstrobel/mailtm/blob/e5d5628d24b8f3505e61d8b7f60d2b3c0e809201/messages.go#L60

In this case, the API returns an error like:
```
{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","detail":"Page should not be less than 1"}
```
And this can't of course not be serialized into an `mailtm.Message` :)

The fix is to follow the error details and start page with one.

Nevertheless, I think it make sense to return an correct error instead of trying to parse the Message...
